//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;

[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("TelegraphConnector.Test")]
[assembly: System.Reflection.AssemblyCompanyAttribute("MarcosCostaDev")]
[assembly: System.Reflection.AssemblyConfigurationAttribute("Debug")]
[assembly: System.Reflection.AssemblyCopyrightAttribute("MarcosCostaDev © 2022")]
[assembly: System.Reflection.AssemblyDescriptionAttribute(@"Introducing TelegraphConnector - the Nuget package that makes it easy to communicate with the Telegra.ph API. 
With this package, you can create a web page using resources from Telegra.ph, giving you access to a wide range of features and functionality. 
Whether you want to publish articles, or share multimedia content, TelegraphConnector makes it simple to do so. 
Simply install the package, create or authenticate with your Telegra.ph account, and start building your web page for using the instant view in the Telegram.  
With easy-to-use methods and comprehensive documentation, TelegraphConnector is the perfect choice for anyone looking to utilize the power of Telegra.ph.")]
[assembly: System.Reflection.AssemblyFileVersionAttribute("1.0.0.0")]
[assembly: System.Reflection.AssemblyInformationalVersionAttribute("1.0.0")]
[assembly: System.Reflection.AssemblyProductAttribute("TelegraphConnector")]
[assembly: System.Reflection.AssemblyTitleAttribute("TelegraphConnector")]
[assembly: System.Reflection.AssemblyVersionAttribute("1.0.0.0")]
[assembly: System.Reflection.AssemblyMetadataAttribute("RepositoryUrl", "https://github.com/MarcosCostaDev/TelegraphConnector.git")]

// Generated by the MSBuild WriteCodeFragment class.

