//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;

[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("TelegraphConnector.Test")]
[assembly: System.Reflection.AssemblyCompanyAttribute("Marcos Costa Dev")]
[assembly: System.Reflection.AssemblyConfigurationAttribute("Debug")]
[assembly: System.Reflection.AssemblyCopyrightAttribute("Marcos Costa Dev © 2022")]
[assembly: System.Reflection.AssemblyDescriptionAttribute("\r\n      Telegra.ph API for .net\r\n      This package allow developers to connect t" +
    "he Telegra.ph API and use its features for create beautiful pages in the Telegra" +
    "m component\r\n    ")]
[assembly: System.Reflection.AssemblyFileVersionAttribute("1.0.0.0")]
[assembly: System.Reflection.AssemblyInformationalVersionAttribute("1.0.0")]
[assembly: System.Reflection.AssemblyProductAttribute("TelegraphConnector")]
[assembly: System.Reflection.AssemblyTitleAttribute("TelegraphConnector")]
[assembly: System.Reflection.AssemblyVersionAttribute("1.0.0.0")]
[assembly: System.Reflection.AssemblyMetadataAttribute("RepositoryUrl", "https://github.com/MarcosCostaDev/TelegraphConnector.git")]

// Generated by the MSBuild WriteCodeFragment class.

