name: Build and test

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

env:
    WORKING_DIR: "$GITHUB_WORKSPACE/src"

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install .NET 7
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore ${{ env.WORKING_DIR }}
    - name: Build solution
      run: dotnet build ${{ env.WORKING_DIR }} --configuration Release
    - name: Test projects
      run: dotnet test ${{ env.WORKING_DIR }} --configuration Release --no-build
